# Generated by Django 6.0.2 on 2026-02-28 21:45

import django.db.models.deletion
import utils.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_allergy_created_at_alter_allergy_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVisit',
            fields=[
                ('id', models.UUIDField(default=utils.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('branch', models.CharField(db_index=True, max_length=100)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('triage_level', models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('stable', 'Stable')], max_length=20)),
                ('arrival_mode', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('admitted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_visits', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
