# Generated by Django 6.0.2 on 2026-02-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_drug_created_at_alter_drug_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
