# Generated by Django 6.0.2 on 2026-02-28 21:45

import django.db.models.deletion
import utils.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicReport',
            fields=[
                ('id', models.UUIDField(default=utils.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('branch', models.CharField(db_index=True, max_length=100)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('sql_query', models.TextField()),
                ('output_format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], default='csv', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
