# Generated by Django 4.2.17 on 2026-02-28 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('adt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, help_text='mmHg', null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, help_text='mmHg', null=True)),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, help_text='bpm', null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='adt.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vital signs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('medication', 'Medication'), ('observation', 'Observation'), ('incident', 'Incident'), ('handover', 'Handover')], default='general', max_length=20)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes', to='adt.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('inhaled', 'Inhaled')], max_length=20)),
                ('administered_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications_administered', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='clinical.prescription')),
            ],
            options={
                'ordering': ['-administered_at'],
            },
        ),
    ]
